### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/commerce#1]
I need to take a simple payment as part of node create. It seems that you've started this already. Have you done any work for hooking up payments? How about the payment module? Thanks.

**Comment by signalpoint** [comment]
@cschaub I'm presenting on this topic with a Commerce Guy at DrupalCon Austin. A solid prototype and documentation will be available in early June.

**Comment by chrisschaub** [comment]
Nice!

On Mon, Apr 28, 2014 at 11:16 AM, Tyler Frankenstein <
notifications@github.com> wrote:

> @cschaub https://github.com/cschaub I'm presenting on this topic with a
> Commerce Guy at DrupalCon Austin. A solid prototype and documentation will
> be available in early June.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/commerce/issues/1#issuecomment-41578737
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by scotthooker** [comment]
@chrisschaub we are implementing the paypal payment system as a base. The issue is relating to sending details to drupal then onto a payment gateway. This method isn't secure.

For the most part we can leverage all of commerce and just interface with drupal that way. For payment we have to interface directly with the gateways.

**Comment by signalpoint** [comment]
Stripe payments now work!
